backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use backend\models\Embassy;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $embassy = Embassy::find()->orderBy('id ASC')->all();
        return $this->render('index',[
            'embassy' => $embassy,
        ]);
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\base\InvalidParamException;
use yii\data\Pagination;
use yii\web\BadRequestHttpException;
use frontend\components\BaseController;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use backend\models\News;
use backend\models\Service;
use backend\models\Energy;
use backend\models\Carenergy;
use backend\models\Car;
use backend\models\Sayt;
use backend\models\Links;
use backend\models\Section;


/**
 * Site controller
 */
class SiteController extends BaseController
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * @inheritdoc
     */

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {

        $slide_news = News::find()->andWhere(['slider'=>[1],'active'=>[1]])->orderBy('id DESC')->limit(8)->all();
        $services = Service::find()->andWhere(['active'=>[1]])->orderBy('order_s ASC')->limit(3)->all();
        $energy = Energy::find()->andWhere(['active_is'=>[1]])->orderBy('id DESC')->limit(12)->all();
        $topenergy = Energy::find()->andWhere(['active_is'=>[1]])->orderBy('show DESC')->limit(15)->all();
        $links = Links::find()->andWhere(['active'=>[1]])->orderBy('id DESC')->all();
        $sayts = Sayt::find()->orderBy('id DESC')->all();
        $cars = Car::find()->orderBy('id DESC')->all();

        return $this->render('index',[
           'slide_news' => $slide_news,
           'services' => $services,
           'energy' => $energy,
           'topenergy' => $topenergy,
           'links'=>$links,
           'sayts' => $sayts,
           'cars' => $cars,
       ]);
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    // public function actionContact()
    // {
    //     $model = new ContactForm();
    //     if ($model->load(Yii::$app->request->post()) && $model->validate()) {
    //         if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
    //             Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
    //         } else {
    //             Yii::$app->session->setFlash('error', 'There was an error sending your message.');
    //         }

    //         return $this->refresh();
    //     } else {
    //         return $this->render('contact', [
    //             'model' => $model,
    //         ]);
    //     }
    // }


    public function actionContacts()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending your message.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }
    public function actionSearch($q = NULL)
    {

       // echo $q;
        // $this->layout = 'columnAgency';
        if($q){
            $model = new \frontend\models\Search();
            $model->q = $q;
            $result = $model->search();
        }else{
            $result = [];
        }

        $services = Service::find()->andWhere(['active'=>[1],'user_id'=>[16,36,1]])->andWhere(['like', 'user_ids', 'adminxitoy'])->orderBy('order_s ASC')->all();


        return $this->render('search', [
           'services' => $services,
           'result' => $result,
       ]);
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        $sections = Section::find()->all();
        $services = Service::find()->andWhere(['active'=>[1],'user_id'=>[16,36,1]])->andWhere(['like', 'user_ids', 'adminxitoy'])->orderBy('order_s ASC')->all();


        return $this->render('about',[
           'services' => $services,
           'sections'=>$sections,
       ]);
    }

    public function actionFilter($car_id)
    {
        $query = Carenergy::find()->Where(['car_id'=>$car_id])->with('energy')->with('car');
        //$query = Article::find()->where(['status' => 1]);
        $countQuery = clone $query;
        $pages = new Pagination(['totalCount' => $countQuery->count()]);
        $models = $query->offset($pages->offset)
        ->limit($pages->limit)
        ->all();
        $services = Service::find()->andWhere(['active'=>[1]])->orderBy('order_s ASC')->limit(3)->all();
        $mashina = Car::find()->orderBy('id Desc')->all();
        $links = Links::find()->andWhere(['active'=>[1]])->orderBy('id DESC')->all();
        $cars = array();
        return $this->render('filter',[
            // 'cars' => $cars,
           'pages' => $pages,
           'models' => $models,
           'services'=>$services,
           'links' => $links,
           'mashina' => $mashina,
           'cars' => $cars,
       ]);
    }

    public function actionList()
    {

        $selection=(array)Yii::$app->request->get('selection');
        $services = Service::find()->andWhere(['active'=>[1]])->orderBy('order_s ASC')->limit(3)->all();
        $mashina = Car::find()->orderBy('id Desc')->all();
        $links = Links::find()->andWhere(['active'=>[1]])->orderBy('id DESC')->all();
        $cars = Car::find()->where(['id' => $selection])->all();

        $query = Carenergy::find()->where(['car_id'=>$selection])
        ->with('energy')
        ->with('car');
        $countQuery = clone $query;
        $pages = new Pagination(['totalCount' => $countQuery->count()]);
        $models = $query->offset($pages->offset)
        ->limit($pages->limit)
        ->all();

        return $this->render('filter',[
          'pages' => $pages,
          'models' => $models,
          'services'=>$services,
          'links' => $links,
          'mashina' => $mashina,
          'cars' => $cars,
      ]);
    }

    public function actionMaps()
    {
        $sections = Section::find()->all();

        return $this->render('maps',[
            'sections'=>$sections,
        ]);
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    // public function actionSignup()
    // {
    //     $model = new SignupForm();
    //     if ($model->load(Yii::$app->request->post())) {
    //         if ($user = $model->signup()) {
    //             if (Yii::$app->getUser()->login($user)) {
    //                 return $this->goHome();
    //             }
    //         }
    //     }

    //     return $this->render('signup', [
    //         'model' => $model,
    //     ]);
    // }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for the provided email address.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {

frontend/views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;
use backend\models\Menu;
use backend\models\SubMenu;
use backend\models\Symbol;
use backend\models\TopMenu;
use backend\models\Chapter;
use backend\models\Article;


use yii\helpers\Url;

$menus = Menu::find()->andWhere(['active'=>[1]])->all();
$symbol= Symbol::find()->all();
$topmenus = TopMenu::find()->all();
$lang = Yii::$app->language;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;

?>



<div class="page animsition" style="top: 40px;">
    <div class="page-content container-fluid">
      <div class="row">
        <div class="col-md-9">
          <!-- Panel -->
          <div class="panel">
            <div class="panel-body nav-tabs-animate nav-tabs-horizontal">
              <div class="tab-content">
                <!-- <div class="tab-pane active animation-slide-left" id="activities" role="tabpanel">1111 -->
                  <center>
                    <img alt="uzbekistan.org"   src="/images/kons_<?= $lang?>.jpg" class="img-responsive" >
                  </center><br>
                  <h4 style="text-align: center;">
                            <?= Yii::t('app', 'muqaddima') ?>
                        </h4>
                        <p style="text-align: justify; font-family: Arial; font-size: 16px;">
                            <?= Yii::t('app', 'muqaddima_text') ?>
                        </p>
                        <!-- Example Continuous Accordion -->
                        <div class="examle-wrap">
                          <div class="example">
                            <div class="panel-group panel-group-continuous" id="exampleAccordionContinuous"
                            aria-multiselectable="true" role="tablist">

                              <?php $i=0;?>
                                <?php $a = 0;?>
                                <?php foreach ($sections as $key => $section):?>
                                    <?php $i++;?>
                              <div class="panel1" >
                                <div class="panel-heading" id="exampleHeadingContinuous<?= $i;?>" role="tab">
                                  <a class="panel-title" data-parent="#exampleAccordionContinuous" data-toggle="collapse"
                                  href="#exampleCollapseContinuousa<?= $i;?>" aria-controls="exampleCollapseContinuous<?= $i;?>"
                                  aria-expanded="false" style="color:#3A469D; ">
                                  <?= $section[$lang.'_section'];?>
                                </a>
                                </div>
                                <div class="panel-collapse collapse" id="exampleCollapseContinuousa<?= $i;?>" aria-labelledby="exampleHeadingContinuous<?= $i;?>"
                                role="tabpanel">
                                  <div class="panel-body">
                                    <?php $chapters = Chapter::find()->where(['section_id' => [$section->id]])->all(); ?>
                                                 <?php if ($chapters):?>
                                                    <?php foreach ($chapters as $key => $chapter): ?>
                                                        <?php $a++;?>
                                                        <div class="panel">
                                                            <div class="panel-heading" id="exampleHeadingContinuous<?=$a;?>" role="tab">
                                                              <a style="color:#3A469D;" class="panel-title collapsed" data-parent="#exampleAccordionContinuous" data-toggle="collapse"
                                                              href="#exampleCollapseContinuous<?=$a;?>" aria-controls="exampleCollapseContinuous<?=$a;?>"
                                                              aria-expanded="false">
                                                              <?= $chapter[$lang.'_chapter'];?>
                                                            </a>
                                                            </div>
                                                            <div class="panel-collapse collapse" id="exampleCollapseContinuous<?=$a;?>" aria-labelledby="exampleHeadingContinuous<?=$a;?>"
                                                            role="tabpanel">
                                                              <div class="panel-body">
                                                                    <?php $articles = Article::find()->where(['chapter_id' => [$chapter->id]])->all(); ?>
                                                            <?php if ($articles):?>
                                                                <?php foreach ($articles as $key => $article): ?>
                                                                    <a href="#" data-toggle="modal" data-target="#largeModal<?= $article->id;?>" >
                                                                        <i class="icon fa-search-plus" aria-hidden="true"></i> <?= $article[$lang.'_article'];?>
                                                                    </a><br><br>
                                                                    <div class="modal fade" id="largeModal<?= $article->id;?>" tabindex="-1" role="dialog" aria-labelledby="largeModalLabel" aria-hidden="true">
                                                                    <div class="modal-dialog modal-lg">
                                                                        <div class="modal-content">
                                                                            <div class="modal-header">
                                                                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                                                                <h4 class="modal-title" id="largeModalLabel"><?= $article[$lang.'_article'];?></h4>
                                                                            </div>
                                                                            <div class="modal-body">
                                                                                <?= $article[$lang.'_article_tex'];?>
                                                                                
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                                  <?php endforeach;?>
                                                            <?php endif;?>

                                                              </div>
                                                            </div>
                                                          </div>
                                  <?php endforeach;?>
                                    <?php endif;?>  

                                  </div>
                                </div>
                              </div>
                          <?php endforeach;?>

                            </div>
                          </div>
                        </div>
            <!-- End Example Continuous Accordion -->
                <!-- </div> -->
              </div>
            </div>
          </div>
          <!-- End Panel -->
        </div>
        <div class="col-md-3">
          <!-- Page Widget -->
          <div class="widget widget-shadow text-center">
            <div class="widget-header">
              <div class="widget-header-content">
                    <?php foreach ($services as $key => $service):?>
                        <div class="col-lg-12 col-md-12" >
                          <div class="widget widget-shadow text-center">
                            <div class="widget-header cover overlay" style="height: calc(100% - 100px);">
                              <img class="cover-image" src="/images/ppp.jpg" alt="..." style="height: 100%;">
                              <div class="overlay-panel vertical-align">
                                <div class="vertical-align-middle">
                                  <a class="avatar avatar-100 bg-white margin-bottom-10 margin-xs-0 img-bordered" <?php if($service->page!=NULL):?> href="<?= Url::to(['/page/view', 'id' => $service->page  ])?>"<?php endif;?> href="<?= $service->link;?>" <?php if($service->target==1):?> target="_blank"<?php endif;?> style="width: 214px;border-radius: 0px;">
                                    <img src="<?= $service->icon;?>" alt="" style="border-radius: 0px;">
                                  </a>
                                  <div class="font-size-15" style="color: #0074b4"><?= $service->{$lang.'_name'};?></div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                    <?php endforeach;?>
                
              </div>
            </div>
          </div>
          <!-- End Page Widget -->
        </div>
      </div>
    </div>
  </div>

frontend/views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;



?>

<div class="col-lg-10 col-lg-offset-1" id="wrapper"><br>

    <div class="container">

        <div class="row">
            <h4><?= Yii::t('app', 'Contact') ?></h4>
            <div class="col-md-12">
                <div class="site-contact">
                    

                    <div class="row">
                        <div class="col-lg-5">
                            <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                                <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                                <?= $form->field($model, 'email') ?>

                                <?= $form->field($model, 'subject') ?>

                                <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                                <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                                    'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                                ]) ?>

                                <div class="form-group">
                                    <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                                </div>

                            <?php ActiveForm::end(); ?>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>


frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

frontend/views/site/filter.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;
use backend\models\Menu;
use backend\models\SubMenu;
use backend\models\Symbol;
use backend\models\TopMenu;
use backend\models\Chapter;
use backend\models\Article;
use yii\widgets\LinkPager;


use yii\helpers\Url;
$lang = Yii::$app->language;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="main-content shop-page main-content-grid-right">
  <div class="container">
    <div class="breadcrumbs">
      <a href="#"></a>  <span class="current"></span>
    </div>
    <div class="row">
      <div class="col-xs-12 col-sm-7 col-md-8 col-lg-9 content-offset">
        <div class="main-banner">
          <div class="banner banner-effect1">
            <a href="#"><img src="images/banner22.jpg" alt=""></a>
          </div>
        </div>
        <div class="categories-content">
          <?php if(empty($cars)):?>
          <h4 class="shop-title"><?php echo $models['0']['car']['name_'.$lang];?></h4>
        <?php else:?>
          <h4 class="shop-title"><?php foreach($cars as $key => $car):?>&nbsp;/&nbsp;<?= $car['name_'.$lang];?>&nbsp;/&nbsp;<?php endforeach;?></h4>
        <?php endif;?>
          <div class="top-control box-has-content">
            <div class="control">
              <div class="control-button">
                <a href="#" class="grid-button active"><span class="icon"><i class="fa fa-th-large" aria-hidden="true"></i> </span>Grid</a>
                <a href="#" class="list-button"><span class="icon"><i class="fa fa-th-list" aria-hidden="true"></i></span> List</a>
              </div>
            </div>
          </div>
          <div class="product-container auto-clear grid-style equal-container box-has-content">
            <?php foreach($models as $key => $value):?>
            <div class="product-item layout1 col-ts-12 col-xs-6 col-sm-6 col-md-4 col-lg-4 no-padding">
              <div class="product-inner equal-elem">
                <div class="thumb" style="overflow:hidden; width:271px; height:271px;">
                  <a href="<?= Url::to(['/energy/view', 'id' => $value->energy->id  ])?>" class="quickview-button"><span class="icon"><i class="fa fa-eye" aria-hidden="true"></i></span> <?= Yii::t('app', 'Batafsil') ?></a>
                  <a href="<?= Url::to(['/energy/view', 'id' => $value->energy->id  ])?>" class="thumb-link"><img src="uploads/<?= $value->energy->img1;?>" alt=""></a>
                </div>
                <div class="info">
                  <a href="detail.html" class="product-name"><?= $value->energy->{'name_'.$lang};?></a>
                  <p class="description"><?= $value->energy->{'description_'.$lang};?></p>
                  <div class="price">
                    <span <?php if($value->energy->sell):?>class="del"<?php endif;?>><?= $value->energy->cost;?> <?= Yii::t('app', 'so\'m') ?></span>
                    <?php if($value->energy->sell):?><span class="ins"><?= $value->energy->sell;?> <?= Yii::t('app', 'so\'m') ?></span><?php endif;?>
                  </div>
                </div>
                <div class="group-button">
                  <div class="inner">
                    <a href="#" class="add-to-cart"><span class="text"><?= Yii::t('app', 'Buyurtma berish') ?></span><span class="icon"><i class="fa fa-cart-arrow-down" aria-hidden="true"></i></span></a>
                  </div>
                </div>
              </div>
            </div>
          <?php endforeach;?>
          </div>
          <div class="pagination">
            <?php
                echo LinkPager::widget([
                    'pagination' => $pages,
                ]);
            ?>

          </div>
        </div>
      </div>
      <div class="col-xs-12 col-sm-5 col-md-4 col-lg-3 sidebar">
        <div class="widget widget-categories">
          <h5 class="widgettitle"><?= Yii::t('app', 'Avtomobil turi bo\'yicha') ?></h5>
          <?=Html::beginForm(['site/list'],'get');?>
          <ul class="list-categories">
            <?php foreach ($mashina as $key => $mashin):?>
            <input type="checkbox" id="<?= $mashin->id;?>" name="selection[]" value="<?= $mashin->id;?>"><label for="<?= $mashin->id;?>" class="label-text"><?= $mashin['name_'.$lang]?></label><br>
          <?php endforeach;?>

          </ul>
          <?= Html::submitButton('Filter', ['class' => 'btn btn-info']);?>
          <?= Html::endForm();?>
        </div>
        <div class="widget widget-banner row-banner">
          <div class="banner">
            <a href="#"><img src="images/banner21.jpg" alt=""></a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="brand">
    <div class="container">
      <div class="owl-carousel" data-autoplay="false" data-nav="false" data-dots="false" data-loop="false" data-slidespeed="800" data-margin="30"  data-responsive = '{"0":{"items":2}, "640":{"items":3}, "768":{"items":3}, "1024":{"items":4}, "1200":{"items":5}}'>
        <?php foreach($links as $key => $link):?>
        <div class="brand-item"><a href="<?= $link->link;?>" target="_blank"><img src="uploads/<?= $link->uz_img?>" alt="" title="<?= $link[$lang.'_name']?>"></a></div>
        <?php endforeach;?><div class="brand-item"><a href="#"><img src="images/brand1.jpg" alt=""></a></div>

      </div>
    </div>
  </div>
</div>

frontend/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

                <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <?= $form->field($model, 'rememberMe')->checkbox() ?>

                <div style="color:#999;margin:1em 0">
                    If you forgot your password you can <?= Html::a('reset it', ['site/request-password-reset']) ?>.
                </div>

                <div class="form-group">
                    <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/resetPassword.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ResetPasswordForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Reset password';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-reset-password">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please choose your new password:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'reset-password-form']); ?>

                <?= $form->field($model, 'password')->passwordInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Save', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>